### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by briceburg** [hiebj/gulp-dir#1]
I am running into an `Error: Cannot find module ...` trying to get this working. Here's my simple setup:

```
/gulpfile.js
/tests.d/
/tests.d/test.js
```

``` js
// gulpfile.js
var gulp = require('gulp');
require('gulp-dir')('tests.d');
gulp.task('default',['all']);
```

``` js
// test.js
var gulp = require('gulp');

gulp.task('watchlist', function(){
  console.log('INDEX WATCH');
});

module.exports = {  
  all: 'watchlist'
};
```

error

```

[nesta@acorn tests]$ npm --version
2.11.3
[nesta@acorn tests]$ node --version
v0.12.4

[nesta@acorn tests]$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'tests.d/watchlist.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/nesta/node_modules/gulp-dir/node_modules/require-all/index.js:38:50
    at Array.forEach (native)
    at requireAll (/home/nesta/node_modules/gulp-dir/node_modules/require-all/index.js:21:9)
    at GulpDir (/home/nesta/node_modules/gulp-dir/index.js:11:25)
    at Object.<anonymous> (/home/nesta/git/magento-skel/tests/gulpfile.js:6:20)
    at Module._compile (module.js:460:26)
```

Any ideas? Many thanks!

**Comment by briceburg** [comment]
this had to do with absolute pathing; I update the main gulpfile.js to read:

```
require('gulp-dir')(__dirname + '/tests.d');
```

versus

```
require('gulp-dir')('tests.d');
```

from the documentation
